/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\untitled.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/untitled.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.01}>
          <group scale={2.54}>
            <mesh geometry={nodes['3DGeom-3'].geometry} material={materials['DefaultMaterial~1']} position={[0.709, 0.787, 30.787]} />
            <mesh geometry={nodes['3DGeom-4'].geometry} material={materials['DefaultMaterial~1']} position={[14.364, 23.137, 0]} scale={[1, 1, 1.2]} />
            <mesh geometry={nodes['3DGeom-5'].geometry} material={materials.MDF} position={[15.039, 0.787, 4.724]} />
            <mesh geometry={nodes['3DGeom-6'].geometry} material={materials['[Color M00]1']} position={[-1.969, 0, 0.787]} />
            <mesh geometry={nodes['3DGeom-4001'].geometry} material={materials['DefaultMaterial~1']} position={[0.396, 1.117, 0]} scale={[1, 1, 1.2]} />
            <mesh geometry={nodes['3DGeom-4002'].geometry} material={materials['DefaultMaterial~1']} position={[14.364, 1.117, 0]} scale={[1, 1, 1.2]} />
            <mesh geometry={nodes['3DGeom-9'].geometry} material={materials['DefaultMaterial~1']} position={[-1.26, 0.787, 18.661]} />
            <mesh geometry={nodes['3DGeom-10'].geometry} material={materials['[Carrera Marble]']} position={[0, 0, 31.89]} />
            <mesh geometry={nodes['3DGeom-11'].geometry} material={materials['DefaultMaterial~1']} position={[0.709, 23.701, 21.181]} />
            <mesh geometry={nodes['3DGeom-12'].geometry} material={materials.MDF} position={[-9.134, 21.26, 31.969]} />
            <mesh geometry={nodes['3DGeom-5001'].geometry} material={materials.MDF} position={[0.709, 0.787, 4.724]} rotation={[-Math.PI, 0, 0]} scale={-1} />
            <mesh geometry={nodes['3DGeom-14'].geometry} material={materials['DefaultMaterial~1']} position={[5.236, 23.189, 5.433]} />
            <mesh geometry={nodes['3DGeom-15'].geometry} material={materials.MDF} position={[-9.134, 21.26, 5.433]} rotation={[0, 0, -Math.PI]} scale={-1} />
            <mesh geometry={nodes['3DGeom-16'].geometry} material={materials.MDF} position={[0.709, 0.787, 31.969]} />
            <mesh geometry={nodes['3DGeom-4003'].geometry} material={materials['DefaultMaterial~1']} position={[0.396, 23.137, 0]} scale={[1, 1, 1.2]} />
            <mesh geometry={nodes['3DGeom-18'].geometry} material={materials['DefaultMaterial~1']} position={[0.059, 0.079, 4.783]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/untitled.glb')
